# Configuration-
lib/ext/ [Everything under this directory can be excluded]

      sunjce_provider.jar,sunec.jar, sunpkcs11.jar and sunmscapi.jar - 
  
      JCA/JCE providers for Java Cryptography APIs. Some providers are 
            not available on all OS or Architectures. The runtime environment 
            must contain at least one implementation of each of the required 
            Security algorithms as described in:
  
      http://docs.oracle.com/javase/8/docs/technotes/guides/
      security/StandardNames.html
         
            localedata.jar  - contains many of the resources needed for  
                  non US English locales
            dnsns.jar       - for the InetAddress wrapper of 
                              JNDI DNS provider

   bin/rmid        - [.exe, and .dll on Microsoft Windows] Java RMI Activation 
                     System Daemon
   bin/rmiregistry - Java Remote Object Registry
   bin/tnameserv   - Java IDL Name Server
   bin/keytool     - Key and Certificate Management Tool
   bin/kinit       - [Microsoft Windows] Used to obtain and cache Kerberos 
                     ticket-granting tickets
   bin/klist       - [Microsoft Windows] Kerberos display entries in 
                     credentials cache and keytab
   bin/ktab        - [Microsoft Windows] Kerberos key table manager
   bin/policytool  - Policy File Creation and Management Tool
   bin/orbd        - Object Request Broker Daemon
   bin/servertool  - Java IDL Server Tool

   bin/javaws and 
   lib/javaws.jar  - Java Web Start
   
   lib/jfr and 
   lib/jfr.jar     - Flight Recorder Files

   lib/oblique-fonts/*
   lib/desktop/*
   plugin/*

GET /<WHATSAPP_BUSINESS_ACCOUNT_ID>/message_template_previews
  ?category=AUTHENTICATION,
  &language=<LANGUAGE>, // Optional
  &add_security_recommendation=<ADD_SECURITY_RECOMMENDATION>, // Optional
  &code_expiration_minutes=<CODE_EXPIRATION_MINUTES>, // Optional
  &button_types=<BUTTON_TYPES> // Optional
                self['extralabel'].setTextCol(ExtratextCol)
